<a href="https://colab.research.google.com/github/sravanikagga/git-python-project/blob/main/data_preprocessing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Step - 1 - Import Data from csv
!pip install pandas

In [2]:
import pandas as pd
data=pd.read_csv('Data.csv')

In [3]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
data.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [6]:
data['Country']

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [7]:
data['Country'][0]

'France'

In [8]:
data['Age'][6]

nan

In [9]:
data[0]

KeyError: ignored

In [10]:
data.head(3)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [11]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [12]:
data.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [13]:
data.tail(2)

Country   Age   Salary Purchased
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [14]:
# Step - 2: separate both i/p & o/p
# Y=f(X)
# Independent Variables - Country,Age,Salary
X=data.iloc[:,0:-1].values

In [15]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [16]:
# Dependent Variables
Y=data.iloc[:,-1].values

In [17]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [18]:
# Step -3: Talk about missing data
!pip install sklearn



In [19]:
# Missing data in x
# missing data - nan
from sklearn.impute import SimpleImputer
import numpy as np
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3]) #identification will be done
X[:,1:3]=imputer.transform(X[:,1:3])

In [20]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [21]:
# Step - 4 : Taking care of string data
# Independent Variable at index 0
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=ct.fit_transform(X)

In [22]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [23]:
# Encode the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [24]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [25]:
# Step - 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X[:,3:5]=sc.fit_transform(X[:,3:5])

In [26]:
X

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [27]:
# Step 6: Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [28]:
X_train

array([[1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361]],
      dtype=object)

In [29]:
X_test

array([[0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696]],
      dtype=object)

In [30]:
Y_train

array([1, 0, 0, 1, 0, 1, 0, 1])

In [31]:
Y_test

array([0, 1])